# GFAnalytics Configuration

# Stock/Index Configuration
stock:
  code: "HSI"  # Stock or index code to analyze
  ric_code: "^HSI"  # Reuters Instrument Code - Confirmed working with Ticker().history()
  listing_date: "1969-11-24 08:30:00+08:00"  # HK market open time (GMT+8)
  # listing_date: "2010-06-29 21:30:00+08:00"  # Tesla HK market open time (GMT+8)
  # listing_date: "1950-09-07 07:30:00+08:00"  # Nikke HK market open time (GMT+8)
  # listing_date: "1957-03-04 21:30:00+08:00"  # S&P500 HK market open time (GMT+8) March 4, 1957
  # listing_date: "1999-01-22 21:30:00+08:00"  # NVDA HK market open time (GMT+8)
  # listing_date: "1979-04-01 13:30:00+08:00"  # IRAN HK market open time (GMT+8)
  # listing_date: "1957-03-04 21:30:00+08:00"  # S&P500 HK market open time (GMT+8)
  # listing_date: "1996-09-02 15:30:00+08:00"  # 乌克兰格里夫纳 open time (GMT+8)
  # listing_date: "1979-04-27 13:30:00+08:00"  # Gary Lam open time (GMT+8)

# Additional Stocks Configuration
additional_stocks:
  TSLA:
    code: "TSLA"  # Stock or index code to analyze
    ric_code: "TSLA"  # Reuters Instrument Code
    listing_date: "2010-06-29 21:30:00+08:00"  # NY market open time (9:30 AM ET) converted to GMT+8

# Active stock configuration (which stock to use for current analysis)
active_stock: "HSI"  # Default to HSI, can be changed to "TSLA" when needed

# Date Range Configuration
date_range:
  training:
    start_date: "2019-01-01"  # Start date for training data
    end_date: "2025-06-18"    # End date for training data

  testing:
    start_date: "2025-01-31"  # Start date for testing data
    end_date: "2025-04-31"    # End date for testing data
  prediction:
    start_date: "2025-06-19"  # Base date for future predictions (day after training end)
    days_ahead: 200       # Number of days to predict ahead

# Data Period Configuration
period: "1H"  # Trading period (1H, 2H, 1D, etc.)

# Google Cloud Platform Configuration
gcp:
  project_id: "stock8word"
  credentials_path: "stock8word-70af0959c4cb.json"
  
  # BigQuery Configuration
  bigquery:
    dataset: "GFAnalytics"
    tables:
      stock_data: "stock_data"
      bazi_data: "bazi_data"
      training_data: "training_data"
      prediction_data: "prediction_data"
      model_metrics: "model_metrics"
      batch: "batch"  # New batch table to track batch operations
    
    # HSI Alternative Data Source Configuration
    hsi_data:
      project: "stock8word"
      dataset: "HSI8"
      table: "HSIFROM2019_copy"  # Default table
      available_tables:
        - "HSIFROM2019_copy"
        - "HSI_2017"
  
  # Google Drive Configuration
  gdrive:
    folder_id: "your_gdrive_folder_id"  # Replace with actual folder ID
    model_filename: "gf_model.pkl"

# Model Configuration
model:
  type: "random_forest"
  params:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42
  
  # Feature Engineering
  features:
    use_bazi: true
    use_chengshen: true
    use_technical_indicators: true
    
    # Technical indicators to include
    technical_indicators:
      - "SMA"  # Simple Moving Average
      - "EMA"  # Exponential Moving Average
      - "RSI"  # Relative Strength Index
      - "MACD" # Moving Average Convergence Divergence
      - "BB"   # Bollinger Bands
    
    # Encoding configuration
    encoding:
      method: "label_encoding"  # Options: label_encoding, one_hot_encoding
    
    # Simple column filtering
    filtering:
      enabled: true  # Set to true to enable filtering
      
      # Base pillars filtering (stock listing date Bazi)
      base_pillars:
        include_patterns: []  # Include columns matching these patterns, e.g., ["base_year", "base_month"]
        exclude_patterns: [""]  # Exclude ALL base_ columns
      
      # Current pillars filtering (time-specific Bazi)  
      current_pillars:
        include_patterns: []  # Include columns matching these patterns, e.g., ["current_day", "current_hour"]
        exclude_patterns: [""]  # Exclude ALL current_ columns
      
      # ChengShen filtering
      chengshen:
        include_patterns: []  # Include columns matching these patterns, e.g., ["生", "克"]
        exclude_patterns: []  # Exclude columns matching these patterns
      
      # Custom filtering (applies to all columns)
      custom:
        include_patterns: []  # Include columns matching these patterns
        exclude_patterns: []  # Exclude columns matching these patterns
      
  # Evaluation metrics
  evaluation:
    metrics:
      - "MSE"    # Mean Squared Error
      - "RMSE"   # Root Mean Squared Error
      - "R2"     # R-squared
      - "MedAE"  # Median Absolute Error
    
    # Feature importance analysis
    feature_importance: true
    correlation_heatmap: true

# Visualization Configuration
visualization:
  plot_prediction: true
  plot_feature_importance: true
  plot_correlation_heatmap: true
  save_plots: true
  plots_dir: "plots"
  display_plots_at_end: true  # Whether to show all plots at the end of pipeline
  
  # Moving Average Parameters for Plots
  moving_averages:
    short_period: 21    # Short-term MA period (daily/monthly)
    long_period: 95     # Long-term MA period (quarterly)
    center: true        # Whether to center the moving average
    min_periods_short: 21  # Minimum periods required for short MA
    min_periods_long: 95   # Minimum periods required for long MA

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "gfanalytics.log" 